name: "Cachix Push"
on:
  pull_request:
  push:
jobs:
  addToCachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: emattiza
        # If you chose signing key for write access
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix develop --profile /tmp/buildEnv
    - run: cachix push emattiza /tmp/buildEnv
    - run: |
        runs=$(nix flake show --json --legacy | jq -r '.devShells."x86_64-linux" | keys | join(" ") | @base64')
        for row in $(echo "$runs" | base64 --decode); do
          nix develop .#"$row" --profile /tmp/"$row"
          cachix push emattiza /tmp/"$row"
        done
